
include ../config.mk

SOURCES = Thread.cc ThreadPool.cc Job.cc Fork.cc Scheduler.cc Thread.hh ThreadPool.hh Job.hh Fork.hh Scheduler.hh 
OBJECTS = Thread.o ThreadPool.o Job.o Fork.o Scheduler.o test.o
COUNTERDIR = ../IntelPCM
COUNTEROBJECTS = $(COUNTERDIR)/msr.o $(COUNTERDIR)/pci.o $(COUNTERDIR)/cpucounters.o $(COUNTERDIR)/client_bw.o

HOSTNAME = $(shell uname -n | tr "." "\n" | head -n 1) 

DFLAGS = -D FIND_MACHINE=$(HOSTNAME)

CPFLAGS = $(CFLAGS) $(PFLAGS)

%.o:	%.cc collect.hh quickSort.hh quickHull.hh quickSort2.hh sequence.hh transpose.hh intSort.hh sampleSort.hh quadTreeSort.hh quadTreeSort2.hh libperf.h getperf.hh affinity.hh parse-args.hh machine-config.hh
	$(CCP) -c $(CFLAGS) $(DFLAGS) $(PFLAGS) $(IFLAGS) $< -o $@ 

all: GatherScatter SimulatedMM Map RRM Cilk-RRM RRG Cilk-RRG RGS RScan quickSort quickSort2 awareSampleSort sampleSort test matMul quadTreeSort quadTreeSort2 # thrtest intSort jTest numProcTest testprof

GatherScatter:	../$(LIBVER)  machine-config.hh GatherScatter.cc GatherScatter.o 
	$(CCP) $(CPFLAGS) -o GatherScatter GatherScatter.o ../$(LIBVER)  $(LFLAGS)

SimulatedMM:	../$(LIBVER)  machine-config.hh SimulatedMM.cc SimulatedMM.o
	$(CCP) $(CPFLAGS) -o SimulatedMM SimulatedMM.o ../$(LIBVER)  $(LFLAGS)

Map:	../$(LIBVER)  machine-config.hh Map.cc Map.o
	$(CCP) $(CPFLAGS) -o Map Map.o ../$(LIBVER)  $(LFLAGS)

RRM:	../$(LIBVER)  machine-config.hh RRM.cc RRM.o
	$(CCP) $(CPFLAGS) -o RRM RRM.o ../$(LIBVER)  $(LFLAGS)

Cilk-RRM:	Cilk-RRM.cc
	g++ -fcilkplus -lcilkrts -I ../IntelPCM/ -I /home/hsimhadr/gcc-cilk/include/cilk/ -I ../src/ -o Cilk-RRM Cilk-RRM.cc $(COUNTEROBJECTS) 

RRG:	../$(LIBVER)  machine-config.hh RRG.cc RRG.o
	$(CCP) $(CPFLAGS) -o RRG RRG.o ../$(LIBVER)  $(LFLAGS)

Cilk-RRG:	Cilk-RRG.cc
	g++ -fcilkplus -lcilkrts -I ../IntelPCM/ -I /home/hsimhadr/gcc-cilk/include/cilk/ -I ../src/ -o Cilk-RRG Cilk-RRG.cc $(COUNTEROBJECTS) 

awareSampleSort:	../$(LIBVER) machine-config.hh awareSampleSort.cc awareSampleSort.o
	$(CCP) $(CPFLAGS) -o awareSampleSort awareSampleSort.o ../$(LIBVER)  $(LFLAGS)

nawareSampleSort:	../$(LIBVER) machine-config.hh nawareSampleSort.cc nawareSampleSort.o
	$(CCP) $(CPFLAGS) -o nawareSampleSort nawareSampleSort.o ../$(LIBVER)  $(LFLAGS)

RGS:	../$(LIBVER)  machine-config.hh RGS.cc RGS.o
	$(CCP) $(CPFLAGS) -o RGS RGS.o ../$(LIBVER)  $(LFLAGS)

RScan:	../$(LIBVER)  machine-config.hh RScan.cc RScan.o
	$(CCP) $(CPFLAGS) -o RScan RScan.o ../$(LIBVER)  $(LFLAGS)

matMul:	../$(LIBVER) machine-config.hh matMul.cc matMul.o 
	$(CCP) $(CPFLAGS) -o matMul matMul.o ../$(LIBVER)    $(LFLAGS)

thrtest:	../$(LIBVER)  machine-config.hh main.cc main.o 
	$(CCP) $(CPFLAGS) -o thrtest main.o ../$(LIBVER)    $(LFLAGS)

quickSort:	../$(LIBVER)  machine-config.hh quickSort.hh quickSort.cc quickSort.o 
	$(CCP) $(CPFLAGS) -o quickSort quickSort.o ../$(LIBVER)    $(LFLAGS)

quickSort2:	../$(LIBVER)  machine-config.hh quickSort2.hh quickSort2.cc quickSort2.o 
	$(CCP) $(CPFLAGS) -o quickSort2 quickSort2.o ../$(LIBVER)    $(LFLAGS)

quickHull:	../$(LIBVER)  machine-config.hh quickHull.hh quickHull.cc quickHull.o 
	$(CCP) $(CPFLAGS) -o quickHull quickHull.o ../$(LIBVER)    $(LFLAGS)

quadTreeSort:	../$(LIBVER)  machine-config.hh quadTreeSort.hh quadTreeSort.cc quadTreeSort.o 
	$(CCP) $(CPFLAGS) -o quadTreeSort quadTreeSort.o ../$(LIBVER)    $(LFLAGS)

quadTreeSort2:	../$(LIBVER)  machine-config.hh quadTreeSort2.hh quadTreeSort2.cc quadTreeSort2.o 
	$(CCP) $(CPFLAGS) -o quadTreeSort2 quadTreeSort2.o ../$(LIBVER)    $(LFLAGS)

sampleSort:	../$(LIBVER)  machine-config.hh sampleSort.cc sampleSort.o 
	$(CCP) $(CPFLAGS) -o sampleSort sampleSort.o ../$(LIBVER)   $(LFLAGS)

intSort:	../$(LIBVER)  machine-config.hh intSort.hh intSort.cc intSort.o 
	$(CCP) $(CPFLAGS) -o intSort intSort.o ../$(LIBVER)    $(LFLAGS)

test:	../$(LIBVER)  machine-config.hh test.cc test.o 
	$(CCP) $(CPFLAGS) -o test test.o ../$(LIBVER)  $(LFLAGS) 

testprof: ../$(LIBVER)  machine-config.hh test.cc test.o
	$(CCP) $(CPFLAGS) -o testprof test.o ../$(LIBVER)  $(LFLAGS) -pg

jTest:	../$(LIBVER)  machine-config.hh jTest.cc jTest.o 
	$(CCP) $(CPFLAGS) -o jTest jTest.o ../$(LIBVER)   $(LFLAGS)

numProcTest:	../$(LIBVER)  machine-config.hh numProcTest.cc numProcTest.o
	$(CCP) $(CPFLAGS) -o numProcTest numProcTest.o ../$(LIBVER)   $(LFLAGS)

clean:
	rm -rf *.o *~ thrtest matMul

